name: pets_ecommerce
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  auto_size_text: ^2.1.0
  google_fonts: ^0.4.0
#  lottie: ^1.0.1
  cached_network_image: ^2.2.0+1
  get: ^4.3.8
  #get: ^4.1.4
  shape_of_view: ^1.0.2
  custom_navigator: ^0.3.0
  share: ^2.0.1
  video_player:
#  device_preview:
  shared_preferences: ^0.5.10
  dio: ^3.0.10
  cool_alert: ^1.0.3
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  inspection: ^0.0.12
  basic_utils: ^2.5.3
  animate_icons: ^2.0.0
  country_code_picker: ^2.0.2
  image_picker: ^0.6.7+17
  lottie:
  path_provider:
  http:
  url_launcher: ^5.5.0
#  flick_video_player: ^0.3.1
  #story_view: ^0.12.8
#  video_thumbnail: ^0.3.3
  export_video_frame: ^0.0.1
  flutter_video_info: ^1.2.0
  video_thumbnail_generator: ^0.0.8
  flutter_swiper: ^1.1.6
  google_maps_flutter: ^1.2.0
  google_map_location_picker: ^4.1.6
  flutter_polyline_points:
  pretty_dio_logger: ^1.1.1
  custom_info_window:
#  bitmap: ^0.1.2
  clippy_flutter: ^1.1.1
  rating_dialog: ^2.0.1
  geolocator: ^6.1.4
  easy_localization:
  syncfusion_flutter_sliders:

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:

    - assets/images/auth/
    - assets/images/bottom_navigation_bar/
    - assets/images/bottom_sheet/
    - assets/images/doctors/
    - assets/images/doctors/active/
    - assets/images/doctors/not_active/
    - assets/images/favorite/notActive/
    - assets/images/favorite/active/
    - assets/images/favorite/
    - assets/images/home/
    - assets/images/splash_screen/
    - assets/images/store/
    - assets/images/store/active/
    - assets/images/store/not active/
    - assets/images/vendor_app/
    - assets/images/
    - assets/images/drawer/drawer_icons/
    - assets/images/drawer/
    - assets/images/profile/
    - assets/translations/




