name: pets_ecommerce
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  auto_size_text: ^2.1.0
  google_fonts: ^0.4.0
#  lottie: ^1.0.1
  cached_network_image: ^2.2.0+1
  get: ^4.1.4
  shape_of_view: ^1.0.2
  custom_navigator: ^0.3.0
  share: ^2.0.1
#  device_preview:
  shared_preferences: ^0.5.10
  dio: ^3.0.10
  cool_alert: ^1.0.3
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  inspection: ^0.0.12
  basic_utils: ^2.5.3
  animate_icons: ^2.0.0
  country_code_picker: ^2.0.2
  image_picker: ^0.6.7+17
  lottie:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:

    - assets/images/auth/
    - assets/images/bottom_navigation_bar/
    - assets/images/bottom_sheet/
    - assets/images/doctors/
    - assets/images/doctors/active/
    - assets/images/doctors/not_active/
    - assets/images/favorite/notActive/
    - assets/images/favorite/active/
    - assets/images/favorite/
    - assets/images/home/
    - assets/images/splash_screen/
    - assets/images/store/
    - assets/images/store/active/
    - assets/images/store/not active/
    - assets/images/vendor_app/
    - assets/images/
    - assets/images/drawer/drawer_icons/
    - assets/images/drawer/
    - assets/images/profile/




